using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using CSVParserTool;

public static class CsvClassGenerator
{
    private const string IfUniTask = "#if UNITASK_INSTALLED";
    private const string ElseNoUniTask = "#else";
    private const string EndIf = "#endif";
    public static string DataRecordClassNameFromFileBaseName(string fileNameWithoutExtension)
    {
        string raw = fileNameWithoutExtension?.Trim() ?? "Sheet";

        if (raw.StartsWith("DT_", StringComparison.OrdinalIgnoreCase))
        {
            raw = raw.Substring(3).Trim();
            if (string.IsNullOrEmpty(raw))
                raw = "Sheet";
        }

        string body = CsvTableParser.SanitizeIdentifier(raw);
        if (string.IsNullOrEmpty(body) || body == "_")
            body = "Sheet";

        // DT_CharacterStatData.xlsx → CharacterStatData (Data 접미사 중복 방지)
        if (body.EndsWith("Data", StringComparison.OrdinalIgnoreCase) && body.Length > 4)
            body = body.Substring(0, body.Length - 4);

        return CsvTableParser.SanitizeIdentifier(body + "Data");
    }

    /// <summary>XLSX 첫 시트 → <see cref="CsvTableParseResult"/> (버전·타입 행 포함 원본 기준).</summary>
    public static CsvTableParseResult ParseTableFromXlsx(
        string xlsxPath,
        string fileNameWithoutExtension = null,
        CsvParseOptions options = null)
    {
        if (string.IsNullOrWhiteSpace(xlsxPath) || !File.Exists(xlsxPath))
            throw new FileNotFoundException("XLSX not found.", xlsxPath);

        string temp = Path.Combine(Path.GetTempPath(), "DataToolCsv_" + Guid.NewGuid().ToString("N") + ".csv");
        try
        {
            XlsxToCsvConverter.ExportFirstWorksheetToCsv(xlsxPath, temp);
            string stem = string.IsNullOrWhiteSpace(fileNameWithoutExtension)
                ? Path.GetFileNameWithoutExtension(xlsxPath)
                : fileNameWithoutExtension;
            string className = DataRecordClassNameFromFileBaseName(stem);
            return CsvTableParser.Parse(temp, className, options);
        }
        finally
        {
            try
            {
                if (File.Exists(temp))
                    File.Delete(temp);
            }
            catch
            {
            }
        }
    }

    /// <summary>XLSX 첫 시트를 임시 CSV로 내보낸 뒤 <see cref="GenerateTableContainerFile(CsvTableParseResult)"/> 와 동일.</summary>
    public static string GenerateTableContainerFileFromXlsx(string xlsxPath)
    {
        string stem = Path.GetFileNameWithoutExtension(xlsxPath);
        return GenerateTableContainerFile(ParseTableFromXlsx(xlsxPath, stem));
    }

    /// <summary>UI 미리보기 전용: XLSX 앞부분만 읽어 빠르게 코드 스케치를 생성합니다.</summary>
    public static string GeneratePreviewFromXlsxFast(string xlsxPath, int maxRows = 64, string exportVersion = null)
    {
        string csv = XlsxToCsvConverter.ConvertXlsxToCsvString(xlsxPath, maxRows);
        string[] lines = csv
            .Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries);

        if (lines.Length < 1)
            throw new InvalidOperationException("Preview requires at least a header row.");

        string sheetName = Path.GetFileNameWithoutExtension(xlsxPath);
        string className = DataRecordClassNameFromFileBaseName(string.IsNullOrWhiteSpace(sheetName) ? "Sheet" : sheetName);
        var options = string.IsNullOrWhiteSpace(exportVersion)
            ? null
            : new CsvParseOptions { ExportVersion = exportVersion.Trim() };
        return GenerateTableContainerFile(CsvTableParser.ParseLines(lines, className, options));
    }

    public static string GenerateTableContainerFile(string csvPath, string classNameOverride = null, CsvParseOptions options = null) =>
        GenerateTableContainerFile(CsvTableParser.Parse(csvPath, classNameOverride, options));

    public static string GenerateTableContainerFile(CsvTableParseResult table)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine(IfUniTask);
        sb.AppendLine("using Cysharp.Threading.Tasks;");
        sb.AppendLine(EndIf);
        sb.AppendLine("using CsvHelper.Configuration.Attributes;");
        sb.AppendLine();
        sb.AppendLine("namespace PJDev.Data");
        sb.AppendLine("{");

        AppendRecordTypeDefinitions(sb, table, out string className);

        sb.AppendLine();
        sb.AppendLine($"    public sealed class {className}Container : DataContainerBase<{className}>");
        sb.AppendLine("    {");
        sb.AppendLine(IfUniTask);
        sb.AppendLine("        public UniTask LoadAsync() => DataSheetLoader.LoadAsync(this);");
        sb.AppendLine(ElseNoUniTask);
        sb.AppendLine("        public void Load() => DataSheetLoader.Load(this);");
        sb.AppendLine(EndIf);
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendRecordTypeDefinitions(StringBuilder sb, string csvPath, string classNameOverride, out string className)
    {
        CsvTableParseResult table = CsvTableParser.Parse(csvPath, classNameOverride);
        AppendRecordTypeDefinitions(sb, table, out className);
    }

    private static void AppendRecordTypeDefinitions(StringBuilder sb, CsvTableParseResult table, out string className)
    {
        className = table.ClassName;

        foreach (string enumName in table.EnumDeclarationOrder)
        {
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            foreach (string v in table.EnumMembers[enumName])
                sb.AppendLine($"        {v},");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    [MessagePackObject]");
        sb.AppendLine("    [System.Serializable]");
        sb.AppendLine($"    public class {className}");
        sb.AppendLine("    {");

        for (int i = 0; i < table.Headers.Length; i++)
        {
            string field = CsvTableParser.SanitizeIdentifier(table.Headers[i]);
            string type = table.ColumnTypes[i];

            CsvColumnReference reference = table.ColumnReferences[i];
            if (reference != null)
                sb.AppendLine($"        /// <summary>{reference.TableName}.{reference.ColumnName} {(reference.IsArray ? "여러 값 참조" : "참조")}</summary>");

            sb.AppendLine($"        [Key({i})]");
            if (CsvColumnTypes.TryGetArrayElementType(type, out string elementType))
            {
                sb.AppendLine($"        [TypeConverter(typeof(PipeSeparatedArrayConverter<{elementType}>))]");
                sb.AppendLine($"        public {type} {field} {{ get; set; }} = System.Array.Empty<{elementType}>();");
            }
            else
            {
                sb.AppendLine($"        public {type} {field} {{ get; set; }}");
            }
        }

        sb.AppendLine("    }");
    }
}
