using System;
using System.Collections.Generic;
using System.Text;

namespace CSVParserTool
{
    public static partial class UnityDataRuntimeGenerator
    {
        private static string BuildGlobalDataContainer(List<string> classNames)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine(IfUniTask);
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine(EndIf);
            sb.AppendLine();
            sb.AppendLine("namespace PJDev.Data");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class GlobalDataContainer");
            sb.AppendLine("    {");

            // ?源???
            sb.AppendLine("        private static GlobalDataContainer instance;");
            sb.AppendLine("        public static GlobalDataContainer Instance => instance ??= new GlobalDataContainer();");
            sb.AppendLine();
            sb.AppendLine("        public DataLoadProgressInfo CurrentLoadInfo { get; private set; }");
            sb.AppendLine("        public event Action<DataLoadProgressInfo> LoadProgressChanged;");
            sb.AppendLine();
            sb.AppendLine("        private void ReportLoadProgress(DataLoadProgressInfo info, Action<DataLoadProgressInfo> callback)");
            sb.AppendLine("        {");
            sb.AppendLine("            CurrentLoadInfo = info;");
            sb.AppendLine("            LoadProgressChanged?.Invoke(info);");
            sb.AppendLine("            callback?.Invoke(info);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ?뚢뫂???瑗?
            foreach (var name in classNames)
            {
                sb.AppendLine($"        private {name}Container {ToCamel(name)}Container;");
                sb.AppendLine($"        public {name}Container {name} => {ToCamel(name)}Container ??= new {name}Container();");
                sb.AppendLine();
            }

            // LoadAll ??DataSheetLoader揶쎛 ?귐뗫탣??깅??곗쨮 筌뤴뫀諭?*Container.LoadAsync ?紐꾪뀱
            sb.AppendLine(IfUniTask);
            sb.AppendLine("        public UniTask LoadTablesOnlyAsync() => LoadTablesOnlyAsync(null);");
            sb.AppendLine("        public UniTask LoadTablesOnlyAsync(Action<DataLoadProgressInfo> progress)");
            sb.AppendLine("            => DataSheetLoader.LoadAllContainersAsync(this, info => ReportLoadProgress(info, progress));");
            sb.AppendLine();
            sb.AppendLine("        public UniTask LoadAllAsync() => LoadAllAsync(null);");
            sb.AppendLine("        public async UniTask LoadAllAsync(Action<DataLoadProgressInfo> progress)");
            sb.AppendLine("        {");
            sb.AppendLine("            var watch = System.Diagnostics.Stopwatch.StartNew();");
            sb.AppendLine("            int tableCount = 0;");
            sb.AppendLine("            await DataSheetLoader.LoadAllContainersAsync(this, info =>");
            sb.AppendLine("            {");
            sb.AppendLine("                tableCount = info.TotalCount;");
            sb.AppendLine("                if (info.State != DataLoadState.Completed)");
            sb.AppendLine("                    ReportLoadProgress(new DataLoadProgressInfo(info.State, info.CurrentTable, info.CompletedCount, info.TotalCount + 1, info.ElapsedMilliseconds, info.ErrorMessage), progress);");
            sb.AppendLine("            });");
            sb.AppendLine("            ReportLoadProgress(new DataLoadProgressInfo(DataLoadState.LoadingInfoStorage, \"InfoStorage\", tableCount, tableCount + 1, watch.ElapsedMilliseconds), progress);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                await InfoStorageRegistry.LoadAllAsync();");
            sb.AppendLine("                ReportLoadProgress(new DataLoadProgressInfo(DataLoadState.Completed, string.Empty, tableCount + 1, tableCount + 1, watch.ElapsedMilliseconds), progress);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                ReportLoadProgress(new DataLoadProgressInfo(DataLoadState.Failed, \"InfoStorage\", tableCount, tableCount + 1, watch.ElapsedMilliseconds, ex.Message), progress);");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine(ElseNoUniTask);
            sb.AppendLine("        public void LoadTablesOnly() => LoadTablesOnly(null);");
            sb.AppendLine("        public void LoadTablesOnly(Action<DataLoadProgressInfo> progress)");
            sb.AppendLine("            => DataSheetLoader.LoadAllContainers(this, info => ReportLoadProgress(info, progress));");
            sb.AppendLine();
            sb.AppendLine("        public void LoadAll() => LoadAll(null);");
            sb.AppendLine("        public void LoadAll(Action<DataLoadProgressInfo> progress)");
            sb.AppendLine("        {");
            sb.AppendLine("            var watch = System.Diagnostics.Stopwatch.StartNew();");
            sb.AppendLine("            int tableCount = 0;");
            sb.AppendLine("            DataSheetLoader.LoadAllContainers(this, info =>");
            sb.AppendLine("            {");
            sb.AppendLine("                tableCount = info.TotalCount;");
            sb.AppendLine("                if (info.State != DataLoadState.Completed)");
            sb.AppendLine("                    ReportLoadProgress(new DataLoadProgressInfo(info.State, info.CurrentTable, info.CompletedCount, info.TotalCount + 1, info.ElapsedMilliseconds, info.ErrorMessage), progress);");
            sb.AppendLine("            });");
            sb.AppendLine("            ReportLoadProgress(new DataLoadProgressInfo(DataLoadState.LoadingInfoStorage, \"InfoStorage\", tableCount, tableCount + 1, watch.ElapsedMilliseconds), progress);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                InfoStorageRegistry.LoadAll();");
            sb.AppendLine("                ReportLoadProgress(new DataLoadProgressInfo(DataLoadState.Completed, string.Empty, tableCount + 1, tableCount + 1, watch.ElapsedMilliseconds), progress);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                ReportLoadProgress(new DataLoadProgressInfo(DataLoadState.Failed, \"InfoStorage\", tableCount, tableCount + 1, watch.ElapsedMilliseconds, ex.Message), progress);");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine(EndIf);
            sb.AppendLine();
            sb.AppendLine("        public void ClearTables()");
            sb.AppendLine("        {");
            foreach (var name in classNames)
                sb.AppendLine($"            {ToCamel(name)}Container?.Clear();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void ClearAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            ClearTables();");
            sb.AppendLine("            InfoStorageRegistry.ClearLoadedData();");
            sb.AppendLine("        }");
            foreach (var name in classNames)
            {
                sb.AppendLine();
                sb.AppendLine($"        public {name} Get{name}(int id) => {name}.Get(id);");
                sb.AppendLine();
                sb.AppendLine($"        public bool TryGet{name}(int id, out {name} data)");
                sb.AppendLine("        {");
                sb.AppendLine($"            data = {name}.Get(id);");
                sb.AppendLine("            return data != null;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string BuildDataContainerBase()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine();
            sb.AppendLine("namespace PJDev.Data");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DataRowId<T>");
            sb.AppendLine("        where T : class");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Func<T, int> Getter = CreateGetter();");
            sb.AppendLine();
            sb.AppendLine("        private static Func<T, int> CreateGetter()");
            sb.AppendLine("        {");
            sb.AppendLine("            PropertyInfo p = typeof(T).GetProperty(");
            sb.AppendLine("                \"Id\",");
            sb.AppendLine("                BindingFlags.Instance | BindingFlags.Public);");
            sb.AppendLine("            if (p == null || p.PropertyType != typeof(int))");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new InvalidOperationException(");
            sb.AppendLine("                    typeof(T).Name + \" must declare public int Id { get; set; }.\");");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            MethodInfo m = p.GetGetMethod();");
            sb.AppendLine("            return (Func<T, int>)Delegate.CreateDelegate(typeof(Func<T, int>), m);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static int Of(T row) => Getter(row);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public abstract class DataContainerBase<T>");
            sb.AppendLine("        where T : class");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly Dictionary<int, T> byId = new Dictionary<int, T>();");
            sb.AppendLine("        private readonly List<T> all = new List<T>();");
            sb.AppendLine();
            sb.AppendLine("        public T Get(int id)");
            sb.AppendLine("        {");
            sb.AppendLine("            return byId.TryGetValue(id, out var row) ? row : null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>嚥≪뮆諭??筌뤴뫀諭?????쀫뱜 ??뽮퐣).</summary>");
            sb.AppendLine("        public IReadOnlyList<T> GetAll() => all;");
            sb.AppendLine();
            sb.AppendLine("        public void Clear()");
            sb.AppendLine("        {");
            sb.AppendLine("            byId.Clear();");
            sb.AppendLine("            all.Clear();");
            sb.AppendLine("        }");
            sb.AppendLine(); sb.AppendLine("        internal void ReplaceFromLoader(IEnumerable<T> rows)");
            sb.AppendLine("        {");
            sb.AppendLine("            Clear();");
            sb.AppendLine("            if (rows != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (T r in rows)");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (r == null)");
            sb.AppendLine("                        continue;");
            sb.AppendLine("                    byId[DataRowId<T>.Of(r)] = r;");
            sb.AppendLine("                    all.Add(r);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}