using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace CSVParserTool
{
    public static class UnityDataRuntimeGenerator
    {
        public const string GlobalDataContainerFileName = "GlobalDataContainer.ToolGenerated.g.cs";
        public const string DataContainerBaseFileName = "DataContainerBase.ToolGenerated.g.cs";
        public const string DataSheetLoaderFileName = "DataSheetLoader.ToolGenerated.g.cs";

        public static void Write(string scriptsDir, IReadOnlyList<string> dataClassNames, Action<string> log)
        {
            if (string.IsNullOrWhiteSpace(scriptsDir))
                throw new ArgumentException("Invalid scripts directory.", nameof(scriptsDir));

            Directory.CreateDirectory(scriptsDir);

            var unique = new List<string>();
            var seen = new HashSet<string>(StringComparer.Ordinal);

            foreach (var name in dataClassNames ?? Array.Empty<string>())
            {
                if (string.IsNullOrWhiteSpace(name) || !seen.Add(name))
                    continue;

                unique.Add(name);
            }

            string obsoleteIdRecord = Path.Combine(scriptsDir, "IDataRecord.ToolGenerated.g.cs");
            if (File.Exists(obsoleteIdRecord))
            {
                File.Delete(obsoleteIdRecord);
                log?.Invoke($"Removed obsolete IDataRecord.ToolGenerated.g.cs (no longer used).");
            }

            string basePath = Path.Combine(scriptsDir, DataContainerBaseFileName);
            File.WriteAllText(basePath, BuildDataContainerBase(), new UTF8Encoding(false));
            log?.Invoke($"Generated: {basePath}");

            string loaderPath = Path.Combine(scriptsDir, DataSheetLoaderFileName);
            File.WriteAllText(loaderPath, BuildDataSheetLoader(), new UTF8Encoding(false));
            log?.Invoke($"Generated: {loaderPath}");

            string oldManagerPath = Path.Combine(scriptsDir, "DataManager.ToolGenerated.g.cs");
            if (File.Exists(oldManagerPath))
            {
                File.Delete(oldManagerPath);
                log?.Invoke("Removed obsolete DataManager.ToolGenerated.g.cs (replaced by GlobalDataContainer).");
            }

            string globalPath = Path.Combine(scriptsDir, GlobalDataContainerFileName);
            File.WriteAllText(globalPath, BuildGlobalDataContainer(unique), new UTF8Encoding(false));
            log?.Invoke($"Generated: {globalPath}");

            foreach (var name in unique)
            {
                string containerPath = Path.Combine(scriptsDir, $"{name}Container.cs");

                if (File.Exists(containerPath))
                    continue;

                File.WriteAllText(containerPath, BuildContainer(name), new UTF8Encoding(false));
                log?.Invoke($"Generated: {containerPath}");
            }
        }

        // =========================
        // GlobalDataContainer 생성
        // =========================
        private static string BuildGlobalDataContainer(List<string> classNames)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace PJDev.Data");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class GlobalDataContainer");
            sb.AppendLine("    {");

            // 싱글톤
            sb.AppendLine("        private static GlobalDataContainer instance;");
            sb.AppendLine("        public static GlobalDataContainer Instance => instance ??= new GlobalDataContainer();");
            sb.AppendLine();

            // 컨테이너
            foreach (var name in classNames)
            {
                sb.AppendLine($"        private {name}Container {ToCamel(name)}Container;");
                sb.AppendLine($"        public {name}Container {name} => {ToCamel(name)}Container ??= new {name}Container();");
                sb.AppendLine();
            }

            // getter dictionary
            sb.AppendLine("        private Dictionary<Type, Func<int, object>> getters;");
            sb.AppendLine();

            // LoadAll — DataSheetLoader가 리플렉션으로 모든 *Container.LoadAsync 호출
            sb.AppendLine("        public async UniTask LoadAllAsync()");
            sb.AppendLine("        {");
            sb.AppendLine("            await DataSheetLoader.LoadAllContainersAsync(this);");
            sb.AppendLine();
            sb.AppendLine("            getters = new Dictionary<Type, Func<int, object>>");
            sb.AppendLine("            {");

            foreach (var name in classNames)
            {
                sb.AppendLine($"                {{ typeof({name}), id => this.{name}.Get(id) }},");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");

            // Get
            sb.AppendLine();
            sb.AppendLine("        public T Get<T>(int id) where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            if (getters != null && getters.TryGetValue(typeof(T), out var getter))");
            sb.AppendLine("                return getter(id) as T;");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");

            // TryGet
            sb.AppendLine();
            sb.AppendLine("        public bool TryGet<T>(int id, out T data) where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            data = Get<T>(id);");
            sb.AppendLine("            return data != null;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string BuildDataContainerBase()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine();
            sb.AppendLine("namespace PJDev.Data");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DataRowId<T>");
            sb.AppendLine("        where T : class");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Func<T, int> Getter = CreateGetter();");
            sb.AppendLine();
            sb.AppendLine("        private static Func<T, int> CreateGetter()");
            sb.AppendLine("        {");
            sb.AppendLine("            PropertyInfo p = typeof(T).GetProperty(");
            sb.AppendLine("                \"Id\",");
            sb.AppendLine("                BindingFlags.Instance | BindingFlags.Public);");
            sb.AppendLine("            if (p == null || p.PropertyType != typeof(int))");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new InvalidOperationException(");
            sb.AppendLine("                    typeof(T).Name + \" must declare public int Id { get; set; }.\");");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            MethodInfo m = p.GetGetMethod();");
            sb.AppendLine("            return (Func<T, int>)Delegate.CreateDelegate(typeof(Func<T, int>), m);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static int Of(T row) => Getter(row);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public abstract class DataContainerBase<T>");
            sb.AppendLine("        where T : class");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly Dictionary<int, T> byId = new Dictionary<int, T>();");
            sb.AppendLine();
            sb.AppendLine("        public T Get(int id)");
            sb.AppendLine("        {");
            sb.AppendLine("            return byId.TryGetValue(id, out var row) ? row : null;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal void ReplaceFromLoader(IEnumerable<T> rows)");
            sb.AppendLine("        {");
            sb.AppendLine("            byId.Clear();");
            sb.AppendLine("            if (rows == null)");
            sb.AppendLine("                return;");
            sb.AppendLine("            foreach (T r in rows)");
            sb.AppendLine("                byId[DataRowId<T>.Of(r)] = r;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildDataSheetLoader()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Unity: com.unity.addressables 필수. 데이터는 Address로만 로드합니다(로컬 경로 없음).");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using CsvHelper;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using MessagePack;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.AddressableAssets;");
            sb.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
            sb.AppendLine();
            sb.AppendLine("namespace PJDev.Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>시트 로드는 <b>Addressables</b>만 사용. <see cref=\"AddressableBytesKeyPrefix\"/> / <see cref=\"AddressableCsvKeyPrefix\"/>에 맞춰 등록하세요.</summary>");
            sb.AppendLine("    public static class DataSheetLoader");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>true면 <c>.bytes</c>만, false면 <c>DT_*.csv</c> TextAsset 우선(실패 시 <c>.bytes</c>).</summary>");
            sb.AppendLine("        public static bool UseBytesFile { get; set; } = !Application.isEditor;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Addressables 주소 접두사. 기본: <c>\"Datas/Bytes/\"</c> + <c>DT_Test.bytes</c>.</summary>");
            sb.AppendLine("        public static string AddressableBytesKeyPrefix { get; set; } = \"Datas/Bytes/\";");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Addressables 주소 접두사. 기본: <c>\"Datas/CSV/\"</c> + <c>DT_Test.csv</c>.</summary>");
            sb.AppendLine("        public static string AddressableCsvKeyPrefix { get; set; } = \"Datas/CSV/\";");
            sb.AppendLine();
            sb.AppendLine("        private static readonly MessagePackSerializerOptions SheetOptions =");
            sb.AppendLine("            MessagePackSerializerOptions.Standard;");
            sb.AppendLine();
            sb.AppendLine("        private static string DataFileStem(string className)");
            sb.AppendLine("        {");
            sb.AppendLine("            string raw = className.EndsWith(\"Data\") && className.Length > 4");
            sb.AppendLine("                ? className.Substring(0, className.Length - 4)");
            sb.AppendLine("                : className;");
            sb.AppendLine("            return \"DT_\" + raw;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string CsvFileName(string className) => DataFileStem(className) + \".csv\";");
            sb.AppendLine();
            sb.AppendLine("        private static string ByteFileName(string className) => DataFileStem(className) + \".bytes\";");
            sb.AppendLine();
            sb.AppendLine("        private static string CsvAddressKey(string className)");
            sb.AppendLine("        {");
            sb.AppendLine("            string stem = DataFileStem(className);");
            sb.AppendLine("            return AddressableCsvKeyPrefix + stem + \".csv\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string ByteAddressKey(string className)");
            sb.AppendLine("        {");
            sb.AppendLine("            string stem = DataFileStem(className);");
            sb.AppendLine("            return AddressableBytesKeyPrefix + stem + \".bytes\";");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static UniTask<T> AwaitHandle<T>(AsyncOperationHandle<T> handle)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (handle.IsDone)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (handle.Status == AsyncOperationStatus.Succeeded)");
            sb.AppendLine("                    return UniTask.FromResult(handle.Result);");
            sb.AppendLine("                if (handle.OperationException != null)");
            sb.AppendLine("                    return UniTask.FromException<T>(handle.OperationException);");
            sb.AppendLine("                return UniTask.FromException<T>(new InvalidOperationException(\"Addressables load failed.\"));");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var utcs = new UniTaskCompletionSource<T>();");
            sb.AppendLine("            handle.Completed += h =>");
            sb.AppendLine("            {");
            sb.AppendLine("                if (h.Status == AsyncOperationStatus.Succeeded)");
            sb.AppendLine("                    utcs.TrySetResult(h.Result);");
            sb.AppendLine("                else if (h.OperationException != null)");
            sb.AppendLine("                    utcs.TrySetException(h.OperationException);");
            sb.AppendLine("                else");
            sb.AppendLine("                    utcs.TrySetException(new InvalidOperationException(\"Addressables load failed.\"));");
            sb.AppendLine("            };");
            sb.AppendLine("            return utcs.Task;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static bool IsDataContainerProperty(Type propertyType)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (Type t = propertyType; t != null && t != typeof(object); t = t.BaseType)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(DataContainerBase<>))");
            sb.AppendLine("                    return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary><see cref=\"GlobalDataContainer\"/>의 public <c>*Container</c> 프로퍼티를 찾아 <c>LoadAsync</c> 호출.</summary>");
            sb.AppendLine("        public static async UniTask LoadAllContainersAsync(GlobalDataContainer global)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (global == null)");
            sb.AppendLine("                throw new ArgumentNullException(nameof(global));");
            sb.AppendLine();
            sb.AppendLine("            var tasks = new List<UniTask>();");
            sb.AppendLine("            foreach (PropertyInfo prop in typeof(GlobalDataContainer).GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!prop.CanRead || !IsDataContainerProperty(prop.PropertyType))");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                object container = prop.GetValue(global);");
            sb.AppendLine("                if (container == null)");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                MethodInfo load = prop.PropertyType.GetMethod(\"LoadAsync\", Type.EmptyTypes);");
            sb.AppendLine("                if (load == null)");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                object ret = load.Invoke(container, null);");
            sb.AppendLine("                if (ret is UniTask ut)");
            sb.AppendLine("                    tasks.Add(ut);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            if (tasks.Count > 0)");
            sb.AppendLine("                await UniTask.WhenAll(tasks.ToArray());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static UniTask LoadAllContainersAsync() => LoadAllContainersAsync(GlobalDataContainer.Instance);");
            sb.AppendLine();
            sb.AppendLine("        public static async UniTask LoadAsync<T>(DataContainerBase<T> container)");
            sb.AppendLine("            where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            string name = typeof(T).Name;");
            sb.AppendLine("            if (!UseBytesFile)");
            sb.AppendLine("            {");
            sb.AppendLine("                string csvKey = CsvAddressKey(name);");
            sb.AppendLine("                AsyncOperationHandle<TextAsset> csvHandle = Addressables.LoadAssetAsync<TextAsset>(csvKey);");
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            sb.AppendLine("                    TextAsset csvTa = await AwaitHandle(csvHandle);");
            sb.AppendLine("                    if (csvTa != null && !string.IsNullOrEmpty(csvTa.text))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        List<T> csvList = await ParseCsvTextAsync<T>(csvTa.text);");
            sb.AppendLine("                        container.ReplaceFromLoader(csvList);");
            sb.AppendLine("                        return;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                catch");
            sb.AppendLine("                {");
            sb.AppendLine("                    /* CSV가 없거나 파싱 실패면 bytes로 폴백 */");
            sb.AppendLine("                }");
            sb.AppendLine("                finally");
            sb.AppendLine("                {");
            sb.AppendLine("                    Addressables.Release(csvHandle);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            string byteKey = ByteAddressKey(name);");
            sb.AppendLine("            AsyncOperationHandle<TextAsset> byteHandle = Addressables.LoadAssetAsync<TextAsset>(byteKey);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                TextAsset byteTa = await AwaitHandle(byteHandle);");
            sb.AppendLine("                if (byteTa == null)");
            sb.AppendLine("                    throw new InvalidOperationException(\"Addressables TextAsset not found: \" + byteKey);");
            sb.AppendLine("                byte[] raw = byteTa.bytes;");
            sb.AppendLine("                List<T> list = await UniTask.RunOnThreadPool(() =>");
            sb.AppendLine("                    MessagePackSerializer.Deserialize<List<T>>(raw, SheetOptions));");
            sb.AppendLine("                container.ReplaceFromLoader(list ?? new List<T>());");
            sb.AppendLine("            }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                Addressables.Release(byteHandle);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static UniTask<List<T>> ParseCsvTextAsync<T>(string text)");
            sb.AppendLine("            where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            return UniTask.RunOnThreadPool(() =>");
            sb.AppendLine("            {");
            sb.AppendLine("                using var reader = new StringReader(text);");
            sb.AppendLine("                using var csv = new CsvReader(reader, CultureInfo.InvariantCulture);");
            sb.AppendLine("                var rows = new List<T>();");
            sb.AppendLine("                foreach (T row in csv.GetRecords<T>())");
            sb.AppendLine("                    rows.Add(row);");
            sb.AppendLine("                return rows;");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildContainer(string name)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated placeholder — export overwrites with full *Container.cs from CSV.>");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace PJDev.Data");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {name}Container : DataContainerBase<{name}>");
            sb.AppendLine("    {");
            sb.AppendLine("        public UniTask LoadAsync() => DataSheetLoader.LoadAsync(this);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string ToCamel(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            return char.ToLowerInvariant(name[0]) + name.Substring(1);
        }
    }
}