using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CSVParserTool.Exporting
{
    public static class UnrealCodeGenerator
    {
        public static string GenerateRowHeader(CsvTableParseResult table, string moduleName)
        {
            if (table == null)
                throw new ArgumentNullException(nameof(table));
            if (string.IsNullOrWhiteSpace(moduleName))
                throw new ArgumentException("Unreal 모듈 이름이 필요합니다.", nameof(moduleName));

            string baseName = RemoveDataSuffix(table.ClassName);
            string rowName = "F" + baseName + "Row";
            string apiMacro = ToApiMacro(moduleName);
            var builder = new StringBuilder(2048);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#pragma once");
            builder.AppendLine();
            builder.AppendLine("#include \"CoreMinimal.h\"");
            builder.AppendLine("#include \"Engine/DataTable.h\"");
            builder.AppendLine("#include \"DataEnums.h\"");
            builder.AppendLine($"#include \"{baseName}Row.generated.h\"");
            builder.AppendLine();

            AppendEnums(builder, table);
            builder.AppendLine("USTRUCT(BlueprintType)");
            builder.AppendLine($"struct {apiMacro} {rowName} : public FTableRowBase");
            builder.AppendLine("{");
            builder.AppendLine("    GENERATED_BODY()");
            builder.AppendLine();

            for (int i = 0; i < table.Headers.Length; i++)
            {
                string propertyName = ToUnrealIdentifier(table.Headers[i]);
                string propertyType = ToUnrealType(table.ColumnTypes[i], table.EnumMembers);
                builder.AppendLine("    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = \"Data Table\")");
                builder.AppendLine($"    {propertyType} {propertyName}{{}};");
                if (i + 1 < table.Headers.Length)
                    builder.AppendLine();
            }

            builder.AppendLine("};");
            return builder.ToString();
        }

        public static string GenerateEnumHeader(EnumCatalog catalog)
        {
            var builder = new StringBuilder(1024);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#pragma once");
            builder.AppendLine();
            builder.AppendLine("#include \"CoreMinimal.h\"");
            bool hasEnums = catalog != null && catalog.DeclarationOrder.Count > 0;
            if (hasEnums)
                builder.AppendLine("#include \"DataEnums.generated.h\"");
            builder.AppendLine();
            if (hasEnums)
            {
                foreach (string enumName in catalog.DeclarationOrder)
                {
                    if (!catalog.Members.TryGetValue(enumName, out IReadOnlyList<string> members))
                        continue;
                    builder.AppendLine("UENUM(BlueprintType)");
                    builder.AppendLine($"enum class {ToEnumTypeName(enumName)} : uint8");
                    builder.AppendLine("{");
                    for (int i = 0; i < members.Count; i++)
                        builder.AppendLine($"    {ToUnrealIdentifier(members[i])}{(i + 1 < members.Count ? "," : string.Empty)}");
                    builder.AppendLine("};");
                    builder.AppendLine();
                }
            }
            return builder.ToString();
        }

        public static string GetRowHeaderFileName(CsvTableParseResult table) =>
            RemoveDataSuffix(table?.ClassName) + "Row.h";
        public static string ToUnrealType(
            string commonType,
            IReadOnlyDictionary<string, IReadOnlyList<string>> knownEnums = null)
        {
            if (CsvColumnTypes.TryGetArrayElementType(commonType, out string elementType))
                return $"TArray<{ToUnrealType(elementType, knownEnums)}>";

            string normalized = commonType?.Trim() ?? "string";
            switch (normalized.ToLowerInvariant())
            {
                case "bool": return "bool";
                case "uint": return "uint32";
                case "int": return "int32";
                case "float": return "float";
                case "double": return "double";
                case "string":
                case "str": return "FString";
                default:
                    if (knownEnums != null && knownEnums.Keys.Any(name =>
                        string.Equals(name, normalized, StringComparison.Ordinal)))
                        return ToEnumTypeName(normalized);
                    throw new NotSupportedException($"Unreal 타입으로 변환할 수 없습니다: {commonType}");
            }
        }

        private static void AppendEnums(StringBuilder builder, CsvTableParseResult table)
        {
            foreach (string enumName in table.EnumDeclarationOrder)
            {
                if (!table.EnumMembers.TryGetValue(enumName, out IReadOnlyList<string> members))
                    continue;

                builder.AppendLine("UENUM(BlueprintType)");
                builder.AppendLine($"enum class {ToEnumTypeName(enumName)} : uint8");
                builder.AppendLine("{");
                for (int i = 0; i < members.Count; i++)
                {
                    string suffix = i + 1 < members.Count ? "," : string.Empty;
                    builder.AppendLine($"    {ToUnrealIdentifier(members[i])}{suffix}");
                }
                builder.AppendLine("};");
                builder.AppendLine();
            }
        }

        private static string ToEnumTypeName(string name)
        {
            string identifier = ToUnrealIdentifier(name);
            return identifier.StartsWith("E", StringComparison.Ordinal) && identifier.Length > 1 && char.IsUpper(identifier[1])
                ? identifier
                : "E" + identifier;
        }

        private static string RemoveDataSuffix(string className)
        {
            string name = ToUnrealIdentifier(className);
            return name.EndsWith("Data", StringComparison.Ordinal) && name.Length > 4
                ? name.Substring(0, name.Length - 4)
                : name;
        }

        private static string ToApiMacro(string moduleName)
        {
            var builder = new StringBuilder(moduleName.Length + 4);
            foreach (char character in moduleName)
            {
                if (char.IsLetterOrDigit(character))
                    builder.Append(char.ToUpperInvariant(character));
                else
                    builder.Append('_');
            }
            return builder.Append("_API").ToString();
        }

        private static string ToUnrealIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new InvalidOperationException("비어 있는 Unreal 식별자는 생성할 수 없습니다.");

            var builder = new StringBuilder(value.Length + 1);
            foreach (char character in value.Trim())
            {
                if (char.IsLetterOrDigit(character) || character == '_')
                    builder.Append(character);
            }
            if (builder.Length == 0)
                throw new InvalidOperationException($"올바른 Unreal 식별자가 아닙니다: {value}");
            if (char.IsDigit(builder[0]))
                builder.Insert(0, '_');
            return builder.ToString();
        }
    }
}
