using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CSVParserTool.Exporting
{
    public static class UnrealCodeGenerator
    {
        public static string GenerateRowHeader(
            CsvTableParseResult table,
            string moduleName,
            IReadOnlyDictionary<string, string> enumTypeNames = null)
        {
            if (table == null)
                throw new ArgumentNullException(nameof(table));
            if (string.IsNullOrWhiteSpace(moduleName))
                throw new ArgumentException("Unreal 모듈 이름이 필요합니다.", nameof(moduleName));
            ValidateForExport(null, new[] { table });

            IReadOnlyDictionary<string, string> resolvedEnumTypeNames = enumTypeNames
                ?? CreateEnumTypeNameMap(table.EnumMembers.Keys);

            string baseName = RemoveDataSuffix(table.ClassName);
            string rowName = "F" + baseName + "Row";
            string apiMacro = ToApiMacro(moduleName);
            var builder = new StringBuilder(2048);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#pragma once");
            builder.AppendLine();
            builder.AppendLine("#include \"CoreMinimal.h\"");
            builder.AppendLine("#include \"Engine/DataTable.h\"");
            builder.AppendLine("#include \"DataEnums.h\"");
            builder.AppendLine($"#include \"{baseName}Row.generated.h\"");
            builder.AppendLine();

            AppendEnums(builder, table, resolvedEnumTypeNames);
            builder.AppendLine("USTRUCT(BlueprintType)");
            builder.AppendLine($"struct {apiMacro} {rowName} : public FTableRowBase");
            builder.AppendLine("{");
            builder.AppendLine("    GENERATED_BODY()");
            builder.AppendLine();

            for (int i = 0; i < table.Headers.Length; i++)
            {
                string propertyName = ToUnrealIdentifier(table.Headers[i]);
                string propertyType = ToUnrealType(table.ColumnTypes[i], table.EnumMembers, resolvedEnumTypeNames);
                builder.AppendLine("    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = \"Data Table\")");
                builder.AppendLine($"    {propertyType} {propertyName}{{}};");
                if (i + 1 < table.Headers.Length)
                    builder.AppendLine();
            }

            builder.AppendLine("};");
            return builder.ToString();
        }

        public static string GenerateEnumHeader(EnumCatalog catalog)
        {
            ValidateForExport(catalog, null);
            var builder = new StringBuilder(1024);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#pragma once");
            builder.AppendLine();
            builder.AppendLine("#include \"CoreMinimal.h\"");
            bool hasEnums = catalog != null && catalog.DeclarationOrder.Count > 0;
            if (hasEnums)
                builder.AppendLine("#include \"DataEnums.generated.h\"");
            builder.AppendLine();
            if (hasEnums)
            {
                IReadOnlyDictionary<string, string> enumTypeNames = CreateEnumTypeNameMap(catalog.DeclarationOrder);
                foreach (string enumName in catalog.DeclarationOrder)
                {
                    if (!catalog.Members.TryGetValue(enumName, out IReadOnlyList<string> members))
                        continue;
                    builder.AppendLine("UENUM(BlueprintType)");
                    builder.AppendLine($"enum class {ResolveEnumTypeName(enumName, enumTypeNames)} : uint8");
                    IReadOnlyDictionary<string, string> memberNames = CreateIdentifierMap(members);
                    builder.AppendLine("{");
                    for (int i = 0; i < members.Count; i++)
                        builder.AppendLine($"    {memberNames[members[i]]}{(i + 1 < members.Count ? "," : string.Empty)}");
                    builder.AppendLine("};");
                    builder.AppendLine();
                }
            }
            return builder.ToString();
        }

        public static string GetRowHeaderFileName(CsvTableParseResult table) =>
            RemoveDataSuffix(table?.ClassName) + "Row.h";
        public static string ToUnrealType(
            string commonType,
            IReadOnlyDictionary<string, IReadOnlyList<string>> knownEnums = null,
            IReadOnlyDictionary<string, string> enumTypeNames = null)
        {
            if (CsvColumnTypes.TryGetArrayElementType(commonType, out string elementType))
                return $"TArray<{ToUnrealType(elementType, knownEnums, enumTypeNames)}>";

            string normalized = commonType?.Trim() ?? "string";
            switch (normalized.ToLowerInvariant())
            {
                case "bool": return "bool";
                case "uint": return "uint32";
                case "int": return "int32";
                case "float": return "float";
                case "double": return "double";
                case "string":
                case "str": return "FString";
                default:
                    if (knownEnums != null && knownEnums.Keys.Any(name =>
                        string.Equals(name, normalized, StringComparison.Ordinal)))
                        return ResolveEnumTypeName(normalized, enumTypeNames);
                    throw new NotSupportedException($"Unreal 타입으로 변환할 수 없습니다: {commonType}");
            }
        }

        private static void AppendEnums(
            StringBuilder builder,
            CsvTableParseResult table,
            IReadOnlyDictionary<string, string> enumTypeNames)
        {
            foreach (string enumName in table.EnumDeclarationOrder)
            {
                if (!table.EnumMembers.TryGetValue(enumName, out IReadOnlyList<string> members))
                    continue;

                builder.AppendLine("UENUM(BlueprintType)");
                builder.AppendLine($"enum class {ResolveEnumTypeName(enumName, enumTypeNames)} : uint8");
                IReadOnlyDictionary<string, string> memberNames = CreateIdentifierMap(members);
                builder.AppendLine("{");
                for (int i = 0; i < members.Count; i++)
                {
                    string suffix = i + 1 < members.Count ? "," : string.Empty;
                    builder.AppendLine($"    {memberNames[members[i]]}{suffix}");
                }
                builder.AppendLine("};");
                builder.AppendLine();
            }
        }

        private static string ToEnumTypeName(string name)
        {
            string identifier = ToUnrealIdentifier(name);
            return identifier.StartsWith("E", StringComparison.Ordinal) && identifier.Length > 1 && char.IsUpper(identifier[1])
                ? identifier
                : "E" + identifier;
        }
        public static void ValidateForExport(
            EnumCatalog catalog,
            IEnumerable<CsvTableParseResult> tables)
        {
            var enumNames = new List<string>();
            List<CsvTableParseResult> tableList = (tables ?? Enumerable.Empty<CsvTableParseResult>())
                .Where(table => table != null)
                .ToList();
            if (catalog != null)
                enumNames.AddRange(catalog.DeclarationOrder);
            foreach (CsvTableParseResult table in tableList)
                enumNames.AddRange(table.EnumDeclarationOrder);

            ValidateEnumTypeNames(enumNames);
            if (catalog != null)
                ValidateEnumMembers(catalog.Members);
            foreach (CsvTableParseResult table in tableList)
                ValidateEnumMembers(table.EnumMembers, table.EnumDeclarationOrder);
        }

        private static void ValidateEnumTypeNames(IEnumerable<string> enumNames)
        {
            var firstByEngineName = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (string enumName in (enumNames ?? Enumerable.Empty<string>()).Distinct(StringComparer.Ordinal))
            {
                string engineName = ToEnumTypeNameBase(enumName);
                if (firstByEngineName.TryGetValue(engineName, out string firstName))
                {
                    throw new InvalidOperationException(
                        $"Unreal Enum 이름 충돌: '{firstName}'와 '{enumName}'은(는) 대소문자만 다르거나 " +
                        $"동일한 Unreal 타입명 '{engineName}'으로 변환됩니다. DT_Enums.xlsx의 EnumName을 서로 다르게 변경하세요.");
                }
                firstByEngineName.Add(engineName, enumName);
            }
        }

        private static void ValidateEnumMembers(
            IReadOnlyDictionary<string, IReadOnlyList<string>> membersByEnum,
            IEnumerable<string> enumNames = null)
        {
            if (membersByEnum == null)
                return;

            IEnumerable<string> names = enumNames ?? membersByEnum.Keys;
            foreach (string enumName in names.Distinct(StringComparer.Ordinal))
            {
                if (!membersByEnum.TryGetValue(enumName, out IReadOnlyList<string> members))
                    continue;

                var firstByEngineName = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                foreach (string member in members ?? Array.Empty<string>())
                {
                    string engineName = ToUnrealIdentifier(member);
                    if (firstByEngineName.TryGetValue(engineName, out string firstMember))
                    {
                        throw new InvalidOperationException(
                            $"Unreal Enum 값 충돌: '{enumName}'의 '{firstMember}'와 '{member}'은(는) " +
                            "대소문자만 달라 Unreal에서 같은 값으로 처리됩니다. Value를 서로 다르게 변경하세요.");
                    }
                    firstByEngineName.Add(engineName, member);
                }
            }
        }
        public static IReadOnlyDictionary<string, string> CreateEnumTypeNameMap(IEnumerable<string> enumNames)
        {
            return CreateCollisionSafeNameMap(enumNames, ToEnumTypeNameBase);
        }

        public static string ToUnrealCsvValue(
            string commonType,
            string value,
            IReadOnlyDictionary<string, IReadOnlyList<string>> knownEnums)
        {
            if (string.IsNullOrEmpty(value) || knownEnums == null)
                return value ?? string.Empty;

            if (CsvColumnTypes.TryGetArrayElementType(commonType, out string elementType))
            {
                return string.Join(
                    "|",
                    CsvColumnTypes.SplitArrayCell(value)
                        .Select(item => ToUnrealCsvValue(elementType, item, knownEnums)));
            }

            string normalizedType = commonType?.Trim() ?? string.Empty;
            if (!knownEnums.TryGetValue(normalizedType, out IReadOnlyList<string> members))
                return value;

            IReadOnlyDictionary<string, string> memberNames = CreateIdentifierMap(members);
            return memberNames.TryGetValue(value.Trim(), out string generatedName)
                ? generatedName
                : value;
        }

        private static IReadOnlyDictionary<string, string> CreateIdentifierMap(IEnumerable<string> names) =>
            CreateCollisionSafeNameMap(names, ToUnrealIdentifier);

        private static IReadOnlyDictionary<string, string> CreateCollisionSafeNameMap(
            IEnumerable<string> names,
            Func<string, string> createBaseName)
        {
            var result = new Dictionary<string, string>(StringComparer.Ordinal);
            var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string name in names ?? Enumerable.Empty<string>())
            {
                if (result.ContainsKey(name))
                    continue;

                string baseName = createBaseName(name);
                string generatedName = baseName;
                int attempt = 0;
                while (!usedNames.Add(generatedName))
                {
                    generatedName = baseName + "_Case" + StableCaseHash(name, attempt).ToString("X8");
                    attempt++;
                }
                result.Add(name, generatedName);
            }
            return result;
        }

        private static uint StableCaseHash(string value, int attempt)
        {
            const uint offset = 2166136261;
            const uint prime = 16777619;
            uint hash = offset;
            string input = (value ?? string.Empty) + "#" + attempt;
            foreach (char character in input)
            {
                hash ^= character;
                hash *= prime;
            }
            return hash;
        }

        private static string ResolveEnumTypeName(
            string name,
            IReadOnlyDictionary<string, string> enumTypeNames)
        {
            if (enumTypeNames != null && enumTypeNames.TryGetValue(name, out string mappedName))
                return mappedName;
            return ToEnumTypeNameBase(name);
        }

        private static string ToEnumTypeNameBase(string name)
        {
            string identifier = ToUnrealIdentifier(name);
            return identifier.StartsWith("E", StringComparison.Ordinal) && identifier.Length > 1 && char.IsUpper(identifier[1])
                ? identifier
                : "E" + identifier;
        }

        private static string RemoveDataSuffix(string className)
        {
            string name = ToUnrealIdentifier(className);
            return name.EndsWith("Data", StringComparison.Ordinal) && name.Length > 4
                ? name.Substring(0, name.Length - 4)
                : name;
        }

        private static string ToApiMacro(string moduleName)
        {
            var builder = new StringBuilder(moduleName.Length + 4);
            foreach (char character in moduleName)
            {
                if (char.IsLetterOrDigit(character))
                    builder.Append(char.ToUpperInvariant(character));
                else
                    builder.Append('_');
            }
            return builder.Append("_API").ToString();
        }

        private static string ToUnrealIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new InvalidOperationException("비어 있는 Unreal 식별자는 생성할 수 없습니다.");

            var builder = new StringBuilder(value.Length + 1);
            foreach (char character in value.Trim())
            {
                if (char.IsLetterOrDigit(character) || character == '_')
                    builder.Append(character);
            }
            if (builder.Length == 0)
                throw new InvalidOperationException($"올바른 Unreal 식별자가 아닙니다: {value}");
            if (char.IsDigit(builder[0]))
                builder.Insert(0, '_');
            return builder.ToString();
        }
    }
}
