using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CSVParserTool.Exporting
{
    internal static class UnrealRuntimeStorageGenerator
    {
        public static void Write(ExportTargetLayout layout, IReadOnlyList<CsvTableParseResult> tables, Action<string> log)
        {
            if (layout == null) throw new ArgumentNullException(nameof(layout));
            List<TableInfo> infos = (tables ?? Array.Empty<CsvTableParseResult>())
                .Where(table => table != null)
                .OrderBy(table => table.ClassName, StringComparer.OrdinalIgnoreCase)
                .Select(CreateTableInfo)
                .ToList();
            Directory.CreateDirectory(layout.GeneratedCodeDirectory);
            Directory.CreateDirectory(layout.GeneratedEditorCodeDirectory);
            var encoding = new UTF8Encoding(false);
            string header = Path.Combine(layout.GeneratedCodeDirectory, "GlobalDataStorage.h");
            string source = Path.Combine(layout.GeneratedEditorCodeDirectory, "GlobalDataStorage.cpp");
            string info = Path.Combine(layout.GeneratedCodeDirectory, "InfoStorage.h");
            GeneratedFileWriter.WriteAllTextIfChanged(header, BuildHeader(layout.ModuleName, infos), encoding);
            GeneratedFileWriter.WriteAllTextIfChanged(source, BuildSource(infos), encoding);
            GeneratedFileWriter.WriteAllTextIfChanged(info, BuildInfoHeader(layout.ModuleName), encoding);
            log?.Invoke("Unreal GlobalDataStorage: " + header);
            log?.Invoke("Unreal InfoStorage: " + info);
        }

        private static string BuildHeader(string moduleName, IReadOnlyList<TableInfo> tables)
        {
            var b = new StringBuilder(4096);
            b.AppendLine("// <auto-generated />");
            b.AppendLine("#pragma once");
            b.AppendLine();
            b.AppendLine("#include \"CoreMinimal.h\"");
            b.AppendLine("#include \"Subsystems/GameInstanceSubsystem.h\"");
            foreach (TableInfo table in tables) b.AppendLine($"#include \"{table.Stem}Row.h\"");
            b.AppendLine("#include \"GlobalDataStorage.generated.h\"");
            b.AppendLine();
            b.AppendLine("class UDataTable;");
            b.AppendLine();
            b.AppendLine("/** Loads every generated DataTable once per game instance and provides typed lookups. */");
            b.AppendLine("UCLASS(BlueprintType)");
            b.AppendLine($"class {ToApiMacro(moduleName)} UGlobalDataStorage final : public UGameInstanceSubsystem");
            b.AppendLine("{");
            b.AppendLine("    GENERATED_BODY()");
            b.AppendLine();
            b.AppendLine("public:");
            b.AppendLine("    UGlobalDataStorage();");
            b.AppendLine("    virtual void Initialize(FSubsystemCollectionBase& Collection) override;");
            b.AppendLine("    virtual void Deinitialize() override;");
            b.AppendLine();
            b.AppendLine("    UFUNCTION(BlueprintPure, Category = \"Data\", meta = (WorldContext = \"WorldContextObject\"))");
            b.AppendLine("    static UGlobalDataStorage* Get(const UObject* WorldContextObject);");
            b.AppendLine();
            b.AppendLine("    UFUNCTION(BlueprintPure, Category = \"Data\")");
            b.AppendLine("    bool IsLoaded() const { return bLoaded; }");
            foreach (TableInfo table in tables)
            {
                b.AppendLine();
                b.AppendLine($"    /** Finds a DT_{table.Stem} row by its Id-backed row name. */");
                b.AppendLine($"    const {table.RowType}* Find{table.Stem}(FName Id) const;");
                b.AppendLine();
                b.AppendLine($"    UFUNCTION(BlueprintPure, Category = \"Data|{table.Stem}\")");
                b.AppendLine($"    bool TryGet{table.Stem}(FName Id, {table.RowType}& OutRow) const;");
                b.AppendLine();
                b.AppendLine($"    UFUNCTION(BlueprintPure, Category = \"Data|{table.Stem}\")");
                b.AppendLine($"    void GetAll{table.Stem}(TArray<{table.RowType}>& OutRows) const;");
            }
            b.AppendLine();
            b.AppendLine("private:");
            b.AppendLine("    UPROPERTY(Transient)");
            b.AppendLine("    bool bLoaded = false;");
            foreach (TableInfo table in tables)
            {
                b.AppendLine();
                b.AppendLine("    UPROPERTY()");
                b.AppendLine($"    TObjectPtr<UDataTable> {table.Stem}Table;");
            }
            b.AppendLine("};");
            return b.ToString();
        }

        private static string BuildSource(IReadOnlyList<TableInfo> tables)
        {
            var b = new StringBuilder(6144);
            b.AppendLine("// <auto-generated />");
            b.AppendLine("#include \"GlobalDataStorage.h\"");
            b.AppendLine("#include \"InfoStorage.h\"");
            b.AppendLine();
            b.AppendLine("#include \"Engine/DataTable.h\"");
            b.AppendLine("#include \"Engine/Engine.h\"");
            b.AppendLine("#include \"Engine/GameInstance.h\"");
            b.AppendLine("#include \"Engine/World.h\"");
            b.AppendLine("#include \"UObject/ConstructorHelpers.h\"");
            b.AppendLine();
            b.AppendLine("UGlobalDataStorage::UGlobalDataStorage()");
            b.AppendLine("{");
            foreach (TableInfo table in tables)
            {
                b.AppendLine($"    static ConstructorHelpers::FObjectFinder<UDataTable> {table.Stem}Finder(");
                b.AppendLine($"        TEXT(\"/Game/PJDevData/DataTables/DT_{table.Stem}.DT_{table.Stem}\"));");
                b.AppendLine($"    {table.Stem}Table = {table.Stem}Finder.Object;");
            }
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("void UGlobalDataStorage::Initialize(FSubsystemCollectionBase& Collection)");
            b.AppendLine("{");
            b.AppendLine("    Super::Initialize(Collection);");
            foreach (TableInfo table in tables)
            {
                b.AppendLine($"    ensureMsgf({table.Stem}Table != nullptr, TEXT(\"DataTable load failed: DT_{table.Stem}\"));");
            }
            b.Append("    bLoaded = ");
            b.AppendLine(tables.Count == 0 ? "true;" : string.Join(" && ", tables.Select(t => t.Stem + "Table != nullptr")) + ";");
            b.AppendLine("    if (bLoaded)");
            b.AppendLine("        FInfoStorageRegistry::BuildAll(*this);");
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("void UGlobalDataStorage::Deinitialize()");
            b.AppendLine("{");
            b.AppendLine("    FInfoStorageRegistry::ClearAll();");
            b.AppendLine("    bLoaded = false;");
            foreach (TableInfo table in tables) b.AppendLine($"    {table.Stem}Table = nullptr;");
            b.AppendLine("    Super::Deinitialize();");
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("UGlobalDataStorage* UGlobalDataStorage::Get(const UObject* WorldContextObject)");
            b.AppendLine("{");
            b.AppendLine("    if (!GEngine || !WorldContextObject) return nullptr;");
            b.AppendLine("    UWorld* World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::ReturnNull);");
            b.AppendLine("    UGameInstance* GameInstance = World ? World->GetGameInstance() : nullptr;");
            b.AppendLine("    return GameInstance ? GameInstance->GetSubsystem<UGlobalDataStorage>() : nullptr;");
            b.AppendLine("}");
            foreach (TableInfo table in tables)
            {
                b.AppendLine();
                b.AppendLine($"const {table.RowType}* UGlobalDataStorage::Find{table.Stem}(FName Id) const");
                b.AppendLine("{");
                b.AppendLine($"    return {table.Stem}Table ? {table.Stem}Table->FindRow<{table.RowType}>(Id, TEXT(\"GlobalDataStorage\"), false) : nullptr;");
                b.AppendLine("}");
                b.AppendLine();
                b.AppendLine($"bool UGlobalDataStorage::TryGet{table.Stem}(FName Id, {table.RowType}& OutRow) const");
                b.AppendLine("{");
                b.AppendLine($"    const {table.RowType}* Row = Find{table.Stem}(Id);");
                b.AppendLine("    if (!Row) return false;");
                b.AppendLine("    OutRow = *Row;");
                b.AppendLine("    return true;");
                b.AppendLine("}");
                b.AppendLine();
                b.AppendLine($"void UGlobalDataStorage::GetAll{table.Stem}(TArray<{table.RowType}>& OutRows) const");
                b.AppendLine("{");
                b.AppendLine("    OutRows.Reset();");
                b.AppendLine($"    if (!{table.Stem}Table) return;");
                b.AppendLine($"    TArray<{table.RowType}*> Rows;");
                b.AppendLine($"    {table.Stem}Table->GetAllRows(TEXT(\"GlobalDataStorage\"), Rows);");
                b.AppendLine("    OutRows.Reserve(Rows.Num());");
                b.AppendLine($"    for (const {table.RowType}* Row : Rows) if (Row) OutRows.Add(*Row);");
                b.AppendLine("}");
            }
            b.AppendLine();
            b.Append(BuildInfoSource());
            return b.ToString();
        }

        private static string BuildInfoHeader(string moduleName)
        {
            var b = new StringBuilder(4096);
            b.AppendLine("// <auto-generated />");
            b.AppendLine("#pragma once");
            b.AppendLine();
            b.AppendLine("#include \"CoreMinimal.h\"");
            b.AppendLine("#include \"GlobalDataStorage.h\"");
            b.AppendLine();
            b.AppendLine("/** Base interface for game-specific data assembled from one or more raw tables. */");
            b.AppendLine("class IInfoStorage");
            b.AppendLine("{");
            b.AppendLine("public:");
            b.AppendLine("    virtual ~IInfoStorage() = default;");
            b.AppendLine("    virtual void Build(const UGlobalDataStorage& Data) = 0;");
            b.AppendLine("    virtual void Clear() {}");
            b.AppendLine("};");
            b.AppendLine();
            b.AppendLine("/** Owns registered InfoStorage instances and rebuilds them after raw tables load. */");
            b.AppendLine($"class {ToApiMacro(moduleName)} FInfoStorageRegistry final");
            b.AppendLine("{");
            b.AppendLine("public:");
            b.AppendLine("    template <typename T>");
            b.AppendLine("    static bool Register()");
            b.AppendLine("    {");
            b.AppendLine("        static_assert(TIsDerivedFrom<T, IInfoStorage>::IsDerived, \"T must derive from IInfoStorage\");");
            b.AppendLine("        return RegisterFactory(TypeKey<T>(), []() -> TUniquePtr<IInfoStorage>");
            b.AppendLine("        {");
            b.AppendLine("            return TUniquePtr<IInfoStorage>(new T());");
            b.AppendLine("        });");
            b.AppendLine("    }");
            b.AppendLine();
            b.AppendLine("    template <typename T>");
            b.AppendLine("    static T* Get()");
            b.AppendLine("    {");
            b.AppendLine("        TUniquePtr<IInfoStorage>* Found = Instances().Find(TypeKey<T>());");
            b.AppendLine("        return Found ? static_cast<T*>(Found->Get()) : nullptr;");
            b.AppendLine("    }");
            b.AppendLine();
            b.AppendLine("    template <typename T>");
            b.AppendLine("    static bool TryGet(T*& OutStorage)");
            b.AppendLine("    {");
            b.AppendLine("        OutStorage = Get<T>();");
            b.AppendLine("        return OutStorage != nullptr;");
            b.AppendLine("    }");
            b.AppendLine();
            b.AppendLine("    static void BuildAll(const UGlobalDataStorage& Data);");
            b.AppendLine("    static void ClearAll();");
            b.AppendLine();
            b.AppendLine("private:");
            b.AppendLine("    using FFactory = TFunction<TUniquePtr<IInfoStorage>()>;");
            b.AppendLine();
            b.AppendLine("    template <typename T>");
            b.AppendLine("    static const void* TypeKey()");
            b.AppendLine("    {");
            b.AppendLine("        static uint8 Key;");
            b.AppendLine("        return &Key;");
            b.AppendLine("    }");
            b.AppendLine();
            b.AppendLine("    static bool RegisterFactory(const void* Key, FFactory Factory);");
            b.AppendLine("    static TMap<const void*, FFactory>& Factories();");
            b.AppendLine("    static TMap<const void*, TUniquePtr<IInfoStorage>>& Instances();");
            b.AppendLine("};");
            b.AppendLine();
            b.AppendLine("#define DATA_TOOL_JOIN_INNER(A, B) A##B");
            b.AppendLine("#define DATA_TOOL_JOIN(A, B) DATA_TOOL_JOIN_INNER(A, B)");
            b.AppendLine("/** Place this macro once in the custom InfoStorage .cpp file. */");
            b.AppendLine("#define REGISTER_INFO_STORAGE(Type) \\");
            b.AppendLine("    namespace { const bool DATA_TOOL_JOIN(GInfoStorageRegistration_, __COUNTER__) = FInfoStorageRegistry::Register<Type>(); }");
            return b.ToString();
        }

        private static string BuildInfoSource()
        {
            var b = new StringBuilder(3072);
            b.AppendLine("// <auto-generated />");
            b.AppendLine("#include \"InfoStorage.h\"");
            b.AppendLine();
            b.AppendLine("TMap<const void*, FInfoStorageRegistry::FFactory>& FInfoStorageRegistry::Factories()");
            b.AppendLine("{");
            b.AppendLine("    static TMap<const void*, FFactory> Value;");
            b.AppendLine("    return Value;");
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("TMap<const void*, TUniquePtr<IInfoStorage>>& FInfoStorageRegistry::Instances()");
            b.AppendLine("{");
            b.AppendLine("    static TMap<const void*, TUniquePtr<IInfoStorage>> Value;");
            b.AppendLine("    return Value;");
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("bool FInfoStorageRegistry::RegisterFactory(const void* Key, FFactory Factory)");
            b.AppendLine("{");
            b.AppendLine("    Factories().Add(Key, MoveTemp(Factory));");
            b.AppendLine("    return true;");
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("void FInfoStorageRegistry::BuildAll(const UGlobalDataStorage& Data)");
            b.AppendLine("{");
            b.AppendLine("    ClearAll();");
            b.AppendLine("    for (const TPair<const void*, FFactory>& Pair : Factories())");
            b.AppendLine("    {");
            b.AppendLine("        TUniquePtr<IInfoStorage> Storage = Pair.Value();");
            b.AppendLine("        if (!Storage)");
            b.AppendLine("            continue;");
            b.AppendLine("        Storage->Build(Data);");
            b.AppendLine("        Instances().Add(Pair.Key, MoveTemp(Storage));");
            b.AppendLine("    }");
            b.AppendLine("}");
            b.AppendLine();
            b.AppendLine("void FInfoStorageRegistry::ClearAll()");
            b.AppendLine("{");
            b.AppendLine("    for (TPair<const void*, TUniquePtr<IInfoStorage>>& Pair : Instances())");
            b.AppendLine("    {");
            b.AppendLine("        if (Pair.Value)");
            b.AppendLine("            Pair.Value->Clear();");
            b.AppendLine("    }");
            b.AppendLine("    Instances().Reset();");
            b.AppendLine("}");
            return b.ToString();
        }
        private static TableInfo CreateTableInfo(CsvTableParseResult table)
        {
            string stem = ToIdentifier(table.ClassName);
            if (stem.EndsWith("Data", StringComparison.Ordinal) && stem.Length > 4) stem = stem.Substring(0, stem.Length - 4);
            return new TableInfo(stem, "F" + stem + "Row");
        }

        private static string ToIdentifier(string value)
        {
            var b = new StringBuilder();
            foreach (char c in (value ?? string.Empty).Trim()) if (char.IsLetterOrDigit(c) || c == '_') b.Append(c);
            if (b.Length == 0) throw new InvalidOperationException("Cannot generate an Unreal storage name: " + value);
            if (char.IsDigit(b[0])) b.Insert(0, '_');
            return b.ToString();
        }

        private static string ToApiMacro(string moduleName)
        {
            var b = new StringBuilder();
            foreach (char c in moduleName ?? string.Empty) b.Append(char.IsLetterOrDigit(c) ? char.ToUpperInvariant(c) : '_');
            return b.Append("_API").ToString();
        }

        private sealed class TableInfo
        {
            public TableInfo(string stem, string rowType) { Stem = stem; RowType = rowType; }
            public string Stem { get; }
            public string RowType { get; }
        }
    }
}
